apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "first-pool"
spec:
  allowFirstLastIPs: "No"
  blocks:
  - start: "172.18.255.200"
    stop: "172.18.255.250"
  - cidr: "192.168.1.0/24"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement-policy
  namespace: kube-system
spec:
  # interfaces:
  # - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true