debug:
  enabled: true
operator:
  replicas: 1
envoy:
  enabled: false
nodeinit:
  enabled: true
  restartPods: true
kubeProxyReplacement: true
k8sServiceHost: "127.0.0.1" #### both neccesary if kubeproxy is missing
k8sServicePort: "6443"      ####
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
ipam:
  mode: kubernetes
l2announcements:
  enabled: true
# hubble:
#   enabled: true
#   ui:
#     enabled: true
#   relay:
#     enabled: 

cluster:
  id: 10
  name: kind-1

# l2podAnnouncements:
#   # -- Enable L2 pod announcements
#   enabled: true
#   # -- Interface used for sending Gratuitous ARP pod announcements
#   interface: "eth0"

# bpf:
#   datapathMode: netkit
#   masquerade: true
#   preallocateMaps: true

# routingMode: native
# localRedirectPolicy: true
# ipv4NativeRoutingCIDR: 10.230.0.0/16
# endpointRoutes:
#   enabled: true
# enableIPv4BIGTCP: true
# cni:
#   exclusive: false