kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-1
nodes:
- role: control-plane
- role: worker
networking:
  # disableDefaultCNI: true
  podSubnet: "10.230.0.0/16"
  serviceSubnet: "10.231.0.0/16"